"""
CRAZYFLIE_MATLAB_CONTROLLER.PY
Webots Native Flight Controller for Bitcraze Crazyflie Drone
Tracks 2D/3D A* Waypoints generated by MATLAB Global Planner
Features:
 - FPV On-board Camera Feed Streaming to disk for MATLAB Live View
 - Real-Time Telemetry & Status Streaming
 - Cascaded Position-Velocity-Attitude PID Loop
"""

import math
import os
import csv
from controller import Robot, GPS, InertialUnit, Gyro, Motor, Camera

def clamp(val, min_val, max_val):
    return max(min_val, min(val, max_val))

class CrazyfliePID:
    def __init__(self):
        self.past_vx_error = 0.0
        self.past_vy_error = 0.0
        self.past_alt_error = 0.0
        self.past_pitch_error = 0.0
        self.past_roll_error = 0.0
        self.altitude_integrator = 0.0

    def pid(self, dt, desired_vx, desired_vy, desired_yaw_rate, desired_altitude,
            actual_roll, actual_pitch, actual_yaw_rate, actual_altitude, actual_vx, actual_vy):
        
        gains = {
            "kp_att_y": 1.0, "kd_att_y": 0.5,
            "kp_att_rp": 0.5, "kd_att_rp": 0.1,
            "kp_vel_xy": 2.0, "kd_vel_xy": 0.5,
            "kp_z": 10.0, "ki_z": 5.0, "kd_z": 5.0
        }

        # Velocity PID -> Desired Pitch & Roll
        vx_error = desired_vx - actual_vx
        vx_deriv = (vx_error - self.past_vx_error) / dt if dt > 0 else 0.0
        vy_error = desired_vy - actual_vy
        vy_deriv = (vy_error - self.past_vy_error) / dt if dt > 0 else 0.0

        desired_pitch = gains["kp_vel_xy"] * clamp(vx_error, -1.0, 1.0) + gains["kd_vel_xy"] * vx_deriv
        desired_roll  = -gains["kp_vel_xy"] * clamp(vy_error, -1.0, 1.0) - gains["kd_vel_xy"] * vy_deriv
        self.past_vx_error = vx_error
        self.past_vy_error = vy_error

        # Altitude PID -> Vertical Thrust
        alt_error = desired_altitude - actual_altitude
        alt_deriv = (alt_error - self.past_alt_error) / dt if dt > 0 else 0.0
        self.altitude_integrator = clamp(self.altitude_integrator + alt_error * dt, -2.0, 2.0)
        alt_command = gains["kp_z"] * alt_error + gains["kd_z"] * alt_deriv + \
                      gains["ki_z"] * self.altitude_integrator + 48.0
        self.past_alt_error = alt_error

        # Attitude PID -> Moments
        pitch_error = desired_pitch - actual_pitch
        pitch_deriv = (pitch_error - self.past_pitch_error) / dt if dt > 0 else 0.0
        roll_error  = desired_roll - actual_roll
        roll_deriv  = (roll_error - self.past_roll_error) / dt if dt > 0 else 0.0
        yaw_rate_error = desired_yaw_rate - actual_yaw_rate

        roll_command  =  gains["kp_att_rp"] * clamp(roll_error, -1.0, 1.0) + gains["kd_att_rp"] * roll_deriv
        pitch_command = -gains["kp_att_rp"] * clamp(pitch_error, -1.0, 1.0) - gains["kd_att_rp"] * pitch_deriv
        yaw_command   =  gains["kp_att_y"]  * clamp(yaw_rate_error, -1.0, 1.0)

        self.past_pitch_error = pitch_error
        self.past_roll_error = roll_error

        # Motor Mixing (Quad X)
        m1 = alt_command - roll_command + pitch_command + yaw_command
        m2 = alt_command - roll_command - pitch_command - yaw_command
        m3 = alt_command + roll_command - pitch_command + yaw_command
        m4 = alt_command + roll_command + pitch_command - yaw_command

        return [clamp(m1, 0.0, 600.0), clamp(m2, 0.0, 600.0),
                clamp(m3, 0.0, 600.0), clamp(m4, 0.0, 600.0)]

def main():
    robot = Robot()
    time_step = int(robot.getBasicTimeStep())
    if time_step <= 0:
        time_step = 32

    robot_name = robot.getName()
    custom_data = robot.getCustomData()
    print(f"=== [Webots Controller Started] Drone: {robot_name} (ID: {custom_data}) ===")

    # Identify Drone 1 or Drone 2
    is_drone_2 = ("2" in custom_data) or ("2" in robot_name)
    csv_name = "astar_path2.csv" if is_drone_2 else "astar_path1.csv"
    
    workspace_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
    csv_path = os.path.join(workspace_root, csv_name)

    waypoints = []
    if os.path.exists(csv_path):
        try:
            with open(csv_path, "r") as f:
                reader = csv.reader(f)
                for row in reader:
                    if row:
                        waypoints.append([float(row[0]), float(row[1])])
            print(f"[{robot_name}] Loaded {len(waypoints)} A* waypoints from {csv_name}")
        except Exception as e:
            print(f"[{robot_name}] Error reading CSV: {e}")

    if not waypoints:
        if is_drone_2:
            waypoints = [[-2.0, -3.8], [-4.0, -3.8], [-6.0, -2.5], [-7.5, -1.2]]
        else:
            waypoints = [[-7.5, -5.0], [-5.5, -5.0], [-4.0, -3.5], [-1.5, -2.5]]

    # Motors
    m1_motor = robot.getDevice("m1_motor")
    m2_motor = robot.getDevice("m2_motor")
    m3_motor = robot.getDevice("m3_motor")
    m4_motor = robot.getDevice("m4_motor")

    for m in [m1_motor, m2_motor, m3_motor, m4_motor]:
        m.setPosition(float('inf'))
        m.setVelocity(0.0)

    # Sensors
    imu = robot.getDevice("inertial_unit")
    imu.enable(time_step)

    gps = robot.getDevice("gps")
    gps.enable(time_step)

    gyro = robot.getDevice("gyro")
    gyro.enable(time_step)

    # Enable FPV Camera
    camera = robot.getDevice("camera")
    if camera:
        camera.enable(time_step)
        print(f"[{robot_name}] FPV Camera enabled ({camera.getWidth()}x{camera.getHeight()})")

    # Initialize PID controller
    pid = CrazyfliePID()
    TARGET_ALTITUDE = 1.0  # Cruise at 1.0m
    WAYPOINT_RADIUS = 0.25 # 25cm acceptance circle

    current_wp_idx = 0
    num_wps = len(waypoints)

    trajectory_log = []
    log_file = os.path.join(workspace_root, f"trajectory_{robot_name}.csv")
    status_file = os.path.join(workspace_root, f"status_{robot_name}.csv")
    img_file = os.path.join(workspace_root, f"camera_{robot_name}.png")

    # Clear previous logs
    for f_del in [log_file, status_file]:
        try:
            if os.path.exists(f_del):
                os.remove(f_del)
        except Exception:
            pass

    # Takeoff stabilization
    while robot.step(time_step) != -1:
        if robot.getTime() > 1.5:
            break

    gps_pos = gps.getValues()
    past_x_global = gps_pos[0]
    past_y_global = gps_pos[1]
    past_time = robot.getTime()

    print(f"[{robot_name}] Commencing trajectory tracking ({num_wps} waypoints)...")

    step_count = 0
    while robot.step(time_step) != -1:
        current_time = robot.getTime()
        dt = current_time - past_time
        if dt <= 0.001:
            dt = time_step / 1000.0

        # Read GPS
        gps_pos = gps.getValues()
        x_act, y_act, z_act = gps_pos[0], gps_pos[1], gps_pos[2]

        # Calculate actual velocities
        vx_global = (x_act - past_x_global) / dt
        vy_global = (y_act - past_y_global) / dt

        rpy = imu.getRollPitchYaw()
        roll_act, pitch_act, yaw_act = rpy[0], rpy[1], rpy[2]
        yaw_rate_act = gyro.getValues()[2]

        cos_y = math.cos(yaw_act)
        sin_y = math.sin(yaw_act)
        actual_vx_body =  vx_global * cos_y + vy_global * sin_y
        actual_vy_body = -vx_global * sin_y + vy_global * cos_y

        # Log position
        trajectory_log.append([current_time, x_act, y_act, z_act])
        step_count += 1
        
        # Target Waypoint
        target_x, target_y = waypoints[current_wp_idx]
        dx = target_x - x_act
        dy = target_y - y_act
        dist_to_wp = math.sqrt(dx*dx + dy*dy)

        # High-frequency telemetry & camera streaming (every 3 steps = ~10 FPS)
        if step_count % 3 == 0:
            try:
                # Save FPV Camera frame
                if camera:
                    camera.saveImage(img_file, 90)

                # Save current real-time status & active targets
                with open(status_file, "w", newline="") as f:
                    writer = csv.writer(f)
                    writer.writerow([current_time, x_act, y_act, z_act, target_x, target_y, current_wp_idx + 1, num_wps])

                # Save trajectory breadcrumbs
                with open(log_file, "w", newline="") as f:
                    writer = csv.writer(f)
                    writer.writerows(trajectory_log)
            except Exception:
                pass

        # Advance waypoint only when near AND at flying height
        if dist_to_wp < WAYPOINT_RADIUS and z_act > 0.4 and current_wp_idx < (num_wps - 1):
            current_wp_idx += 1
            print(f"[{robot_name}] Reached WP {current_wp_idx}/{num_wps} -> Target: [{waypoints[current_wp_idx][0]:.2f}, {waypoints[current_wp_idx][1]:.2f}]")

        # Position controller -> Smooth cruising velocity
        max_speed = 0.25 # m/s
        if dist_to_wp > 0.03:
            desired_vx_global = clamp(0.7 * dx, -max_speed, max_speed)
            desired_vy_global = clamp(0.7 * dy, -max_speed, max_speed)
        else:
            desired_vx_global = 0.0
            desired_vy_global = 0.0

        # Convert desired velocity to body frame
        desired_vx_body =  desired_vx_global * cos_y + desired_vy_global * sin_y
        desired_vy_body = -desired_vx_global * sin_y + desired_vy_global * cos_y

        # Run Bitcraze PID
        motor_speeds = pid.pid(
            dt=dt,
            desired_vx=desired_vx_body,
            desired_vy=desired_vy_body,
            desired_yaw_rate=0.0,
            desired_altitude=TARGET_ALTITUDE,
            actual_roll=roll_act,
            actual_pitch=pitch_act,
            actual_yaw_rate=yaw_rate_act,
            actual_altitude=z_act,
            actual_vx=actual_vx_body,
            actual_vy=actual_vy_body
        )

        # Apply motor commands
        m1_motor.setVelocity(-motor_speeds[0])
        m2_motor.setVelocity( motor_speeds[1])
        m3_motor.setVelocity(-motor_speeds[2])
        m4_motor.setVelocity( motor_speeds[3])

        past_x_global = x_act
        past_y_global = y_act
        past_time = current_time

    # Final Save
    try:
        if camera:
            camera.saveImage(img_file, 90)
        with open(log_file, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerows(trajectory_log)
        print(f"[{robot_name}] Trajectory and camera saved.")
    except Exception as e:
        print(f"[{robot_name}] Save error: {e}")

if __name__ == "__main__":
    main()
