%% CRAZYFLIE_MATLAB_CONTROLLER.M
% Webots MATLAB Controller for Bitcraze Crazyflie Drone
% Follows 2D/3D A* Waypoints generated by MATLAB Planner
% -------------------------------------------------------------

function crazyflie_matlab_controller
    % Initialize Webots API
    TIME_STEP = wb_robot_get_basic_time_step();
    if isempty(TIME_STEP) || TIME_STEP == 0
        TIME_STEP = 32;
    end

    % Identify Robot
    robot_name = wb_robot_get_name();
    custom_data = wb_robot_get_custom_data();
    fprintf('=== [Webots Controller Started] Drone: %s (ID: %s) ===\n', robot_name, custom_data);

    % Robust A* Waypoints File Search
    possible_paths = {
        'astar_paths.mat', ...
        fullfile('c:', 'AStar-Demo', 'astar_paths.mat'), ...
        fullfile(pwd, '..', '..', 'astar_paths.mat'), ...
        fullfile(pwd, '..', 'astar_paths.mat')
    };

    path_loaded = false;
    for i = 1:length(possible_paths)
        if exist(possible_paths{i}, 'file')
            data = load(possible_paths{i});
            if isfield(data, 'path1_webots') && isfield(data, 'path2_webots')
                if strcmp(custom_data, '2') || contains(robot_name, '2')
                    waypoints = data.path2_webots;
                else
                    waypoints = data.path1_webots;
                end
                path_loaded = true;
                fprintf('[%s] Loaded A* waypoints from: %s\n', robot_name, possible_paths{i});
                break;
            end
        end
    end

    if ~path_loaded
        % Fallback default trajectory if not found
        if strcmp(custom_data, '2') || contains(robot_name, '2')
            waypoints = [-2.0, -3.8; -4.0, -3.8; -6.0, -2.5; -7.5, -1.2];
        else
            waypoints = [-7.5, -5.0; -5.5, -5.0; -4.0, -3.5; -1.5, -2.5];
        end
        fprintf('[%s] Using default fallback waypoints.\n', robot_name);
    end

    % Motors setup
    m1_motor = wb_robot_get_device('m1_motor');
    m2_motor = wb_robot_get_device('m2_motor');
    m3_motor = wb_robot_get_device('m3_motor');
    m4_motor = wb_robot_get_device('m4_motor');

    wb_motor_set_position(m1_motor, inf);
    wb_motor_set_position(m2_motor, inf);
    wb_motor_set_position(m3_motor, inf);
    wb_motor_set_position(m4_motor, inf);

    wb_motor_set_velocity(m1_motor, 0.0);
    wb_motor_set_velocity(m2_motor, 0.0);
    wb_motor_set_velocity(m3_motor, 0.0);
    wb_motor_set_velocity(m4_motor, 0.0);

    % Enable Sensors
    imu = wb_robot_get_device('inertial_unit');
    wb_inertial_unit_enable(imu, TIME_STEP);

    gps = wb_robot_get_device('gps');
    wb_gps_enable(gps, TIME_STEP);

    gyro = wb_robot_get_device('gyro');
    wb_gyro_enable(gyro, TIME_STEP);

    % Flight and Controller Parameters
    TARGET_ALTITUDE = 1.0;  % Cruise altitude (meters)
    WAYPOINT_RADIUS = 0.30; % Acceptance radius to advance waypoint (meters)
    current_wp_idx = 1;
    num_wps = size(waypoints, 1);

    % PID Gains
    kp_pos = 1.2;
    kd_pos = 0.35;
    kp_alt = 12.0;
    kd_alt = 5.0;
    ki_alt = 2.0;
    kp_att = 0.6;
    kd_att = 0.15;
    kp_yaw = 1.5;

    % PID States
    past_x_err = 0;
    past_y_err = 0;
    past_alt_err = 0;
    alt_integral = 0;
    past_roll_err = 0;
    past_pitch_err = 0;
    past_time = wb_robot_get_time();

    % Data logging for post-flight analysis
    trajectory_log = [];
    step_count = 0;
    log_name = fullfile('c:', 'AStar-Demo', sprintf('trajectory_%s.mat', robot_name));

    % Stabilization delay (1 second)
    while wb_robot_step(TIME_STEP) ~= -1
        if wb_robot_get_time() > 1.0
            break;
        end
    end

    fprintf('[%s] Commencing A* waypoint tracking (%d waypoints)...\n', robot_name, num_wps);

    %% Main Simulation & Control Loop
    while wb_robot_step(TIME_STEP) ~= -1
        current_time = wb_robot_get_time();
        dt = current_time - past_time;
        if dt <= 0, dt = TIME_STEP / 1000; end

        % Read GPS Position & Velocity
        gps_pos = wb_gps_get_values(gps);
        x_act = gps_pos(1);
        y_act = gps_pos(2);
        z_act = gps_pos(3);

        % Read Attitude (Roll, Pitch, Yaw)
        rpy = wb_inertial_unit_get_roll_pitch_yaw(imu);
        roll_act = rpy(1);
        pitch_act = rpy(2);
        yaw_act = rpy(3);
        yaw_rate_act = wb_gyro_get_values(gyro);
        yaw_rate_act = yaw_rate_act(3);

        % Log state
        trajectory_log = [trajectory_log; current_time, x_act, y_act, z_act];
        step_count = step_count + 1;

        % Periodically save trajectory every 50 steps
        if mod(step_count, 50) == 0
            save(log_name, 'trajectory_log', 'waypoints');
        end

        % Determine Active Waypoint
        target_x = waypoints(current_wp_idx, 1);
        target_y = waypoints(current_wp_idx, 2);
        dist_to_wp = sqrt((target_x - x_act)^2 + (target_y - y_act)^2);

        if dist_to_wp < WAYPOINT_RADIUS && current_wp_idx < num_wps
            current_wp_idx = current_wp_idx + 1;
            fprintf('[%s] Reached WP %d/%d -> Moving to [%.2f, %.2f]\n', ...
                robot_name, current_wp_idx - 1, num_wps, waypoints(current_wp_idx, 1), waypoints(current_wp_idx, 2));
        end

        % Global Position Error
        x_err = target_x - x_act;
        y_err = target_y - y_act;

        % Convert error to drone body frame
        cos_y = cos(yaw_act);
        sin_y = sin(yaw_act);
        x_err_body =  x_err * cos_y + y_err * sin_y;
        y_err_body = -x_err * sin_y + y_err * cos_y;

        % Desired Pitch and Roll from body position error
        desired_pitch = kp_pos * max(min(x_err_body, 1.0), -1.0) + kd_pos * (x_err_body - past_x_err) / dt;
        desired_roll  = - (kp_pos * max(min(y_err_body, 1.0), -1.0) + kd_pos * (y_err_body - past_y_err) / dt);
        past_x_err = x_err_body;
        past_y_err = y_err_body;

        % Altitude Control (PID)
        alt_err = TARGET_ALTITUDE - z_act;
        alt_deriv = (alt_err - past_alt_err) / dt;
        alt_integral = alt_integral + alt_err * dt;
        alt_integral = max(min(alt_integral, 2.0), -2.0);
        thrust_base = 48.0; % Base hovering thrust
        alt_cmd = thrust_base + kp_alt * alt_err + kd_alt * alt_deriv + ki_alt * alt_integral;
        past_alt_err = alt_err;

        % Attitude Control
        pitch_err = desired_pitch - pitch_act;
        roll_err  = desired_roll - roll_act;
        pitch_cmd = -(kp_att * max(min(pitch_err, 1.0), -1.0) + kd_att * (pitch_err - past_pitch_err) / dt);
        roll_cmd  =  (kp_att * max(min(roll_err, 1.0), -1.0)  + kd_att * (roll_err - past_roll_err) / dt);
        yaw_cmd   = -kp_yaw * yaw_rate_act; % Yaw stabilization
        past_pitch_err = pitch_err;
        past_roll_err  = roll_err;

        % Motor Mixer (Quad X configuration)
        m1 = alt_cmd - roll_cmd + pitch_cmd + yaw_cmd;
        m2 = alt_cmd - roll_cmd - pitch_cmd - yaw_cmd;
        m3 = alt_cmd + roll_cmd - pitch_cmd + yaw_cmd;
        m4 = alt_cmd + roll_cmd + pitch_cmd - yaw_cmd;

        % Motor speed limits
        m1 = max(min(m1, 600), 0);
        m2 = max(min(m2, 600), 0);
        m3 = max(min(m3, 600), 0);
        m4 = max(min(m4, 600), 0);

        % Set velocities (opposite rotation signs for counter-rotating propellers)
        wb_motor_set_velocity(m1_motor, -m1);
        wb_motor_set_velocity(m2_motor,  m2);
        wb_motor_set_velocity(m3_motor, -m3);
        wb_motor_set_velocity(m4_motor,  m4);

        past_time = current_time;
    end

    % Final save on exit
    save(log_name, 'trajectory_log', 'waypoints');
    fprintf('[%s] Simulation finished. Trajectory saved to %s.\n', robot_name, log_name);
    wb_robot_cleanup();
end
